package com.miguelaboliveira.svpolitician.ui.theme

import androidx.compose.ui.graphics.Color

public val md_theme_light_primary: Color = Color(0xFF6750A4)
public val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_light_primaryContainer: Color = Color(0xFFEADDFF)
public val md_theme_light_onPrimaryContainer: Color = Color(0xFF21005D)
public val md_theme_light_secondary: Color = Color(0xFF625B71)
public val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_light_secondaryContainer: Color = Color(0xFFE8DEF8)
public val md_theme_light_onSecondaryContainer: Color = Color(0xFF1D192B)
public val md_theme_light_tertiary: Color = Color(0xFF7D5260)
public val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
public val md_theme_light_tertiaryContainer: Color = Color(0xFFFFD8E4)
public val md_theme_light_onTertiaryContainer: Color = Color(0xFF31111D)
public val md_theme_light_error: Color = Color(0xFFB3261E)
public val md_theme_light_onError: Color = Color(0xFFFFFFFF)
public val md_theme_light_errorContainer: Color = Color(0xFFF9DEDC)
public val md_theme_light_onErrorContainer: Color = Color(0xFF410E0B)
public val md_theme_light_outline: Color = Color(0xFF79747E)
public val md_theme_light_background: Color = Color(0xFFFFFBFE)
public val md_theme_light_onBackground: Color = Color(0xFF1C1B1F)
public val md_theme_light_surface: Color = Color(0xFFFFFBFE)
public val md_theme_light_onSurface: Color = Color(0xFF1C1B1F)
public val md_theme_light_surfaceVariant: Color = Color(0xFFE7E0EC)
public val md_theme_light_onSurfaceVariant: Color = Color(0xFF49454F)
public val md_theme_light_inverseSurface: Color = Color(0xFF313033)
public val md_theme_light_inverseOnSurface: Color = Color(0xFFF4EFF4)
public val md_theme_light_inversePrimary: Color = Color(0xFFD0BCFF)
public val md_theme_light_shadow: Color = Color(0xFF000000)
public val md_theme_light_surfaceTint: Color = Color(0xFF6750A4)
public val md_theme_light_outlineVariant: Color = Color(0xFFCAC4D0)
public val md_theme_light_scrim: Color = Color(0xFF000000)

public val md_theme_dark_primary: Color = Color(0xFFD0BCFF)
public val md_theme_dark_onPrimary: Color = Color(0xFF381E72)
public val md_theme_dark_primaryContainer: Color = Color(0xFF4F378B)
public val md_theme_dark_onPrimaryContainer: Color = Color(0xFFEADDFF)
public val md_theme_dark_secondary: Color = Color(0xFFCCC2DC)
public val md_theme_dark_onSecondary: Color = Color(0xFF332D41)
public val md_theme_dark_secondaryContainer: Color = Color(0xFF4A4458)
public val md_theme_dark_onSecondaryContainer: Color = Color(0xFFE8DEF8)
public val md_theme_dark_tertiary: Color = Color(0xFFEFB8C8)
public val md_theme_dark_onTertiary: Color = Color(0xFF492532)
public val md_theme_dark_tertiaryContainer: Color = Color(0xFF633B48)
public val md_theme_dark_onTertiaryContainer: Color = Color(0xFFFFD8E4)
public val md_theme_dark_error: Color = Color(0xFFF2B8B5)
public val md_theme_dark_onError: Color = Color(0xFF601410)
public val md_theme_dark_errorContainer: Color = Color(0xFF8C1D18)
public val md_theme_dark_onErrorContainer: Color = Color(0xFFF9DEDC)
public val md_theme_dark_outline: Color = Color(0xFF938F99)
public val md_theme_dark_background: Color = Color(0xFF1C1B1F)
public val md_theme_dark_onBackground: Color = Color(0xFFE6E1E5)
public val md_theme_dark_surface: Color = Color(0xFF1C1B1F)
public val md_theme_dark_onSurface: Color = Color(0xFFE6E1E5)
public val md_theme_dark_surfaceVariant: Color = Color(0xFF49454F)
public val md_theme_dark_onSurfaceVariant: Color = Color(0xFFCAC4D0)
public val md_theme_dark_inverseSurface: Color = Color(0xFFE6E1E5)
public val md_theme_dark_inverseOnSurface: Color = Color(0xFF313033)
public val md_theme_dark_inversePrimary: Color = Color(0xFF6750A4)
public val md_theme_dark_shadow: Color = Color(0xFF000000)
public val md_theme_dark_surfaceTint: Color = Color(0xFFD0BCFF)
public val md_theme_dark_outlineVariant: Color = Color(0xFF49454F)
public val md_theme_dark_scrim: Color = Color(0xFF000000)

public val seed: Color = Color(0xFF6750A4)
